
const auctionData = [
    {
        id: 1,
        name: "Luxury Car Auction",
        location: "New York, USA",
        dateRange: "12-2-2024 to 12-3-2024",
        lotsAvailable: "12 Lots Available",
        image: "https://link-to-your-image1.jpg",
    },
    {
        id: 2,
        name: "Classic Art Collection",
        location: "New York, USA",
        dateRange: "15-3-2024 to 17-3-2024",
        lotsAvailable: "8 Lots Available",
        image: "https://link-to-your-image2.jpg",
    },
    {
        id: 3,
        name: "Real Estate Auction",
        location: "New York, USA",
        dateRange: "20-4-2024 to 22-4-2024",
        lotsAvailable: "5 Lots Available",
        image: "https://link-to-your-image3.jpg",
    },
    {
        id: 4,
        name: "Vintage Car Showcase",
        location: "New York, USA",
        dateRange: "10-5-2024 to 12-5-2024",
        lotsAvailable: "15 Lots Available",
        image: "https://link-to-your-image4.jpg",
    },
    {
        id: 5,
        name: "Antique Jewelry Auction",
        location: "United Kingdom, London",
        dateRange: "18-6-2024 to 20-6-2024",
        lotsAvailable: "9 Lots Available",
        image: "https://link-to-your-image5.jpg",
    },
    {
        id: 6,
        name: "Sports Memorabilia Sale",
        location: "United Kingdom, London",
        dateRange: "25-7-2024 to 27-7-2024",
        lotsAvailable: "20 Lots Available",
        image: "https://link-to-your-image6.jpg",
    },
    {
        id: 7,
        name: "Modern Art Exhibition",
        location: "United Kingdom, London",
        dateRange: "5-8-2024 to 7-8-2024",
        lotsAvailable: "10 Lots Available",
        image: "https://link-to-your-image7.jpg",
    },
    {
        id: 8,
        name: "Rare Book Auction",
        location: "Pakistan, Islamabad",
        dateRange: "15-9-2024 to 17-9-2024",
        lotsAvailable: "7 Lots Available",
        image: "https://link-to-your-image8.jpg",
    },
    {
        id: 9,
        name: "Collectible Coins Sale",
        location: "Pakistan, Islamabad",
        dateRange: "20-10-2024 to 22-10-2024",
        lotsAvailable: "13 Lots Available",
        image: "https://link-to-your-image9.jpg",
    },
    {
        id: 10,
        name: "Tech Gadgets Auction",
        location: "Pakistan, Islamabad",
        dateRange: "1-11-2024 to 3-11-2024",
        lotsAvailable: "18 Lots Available",
        image: "https://link-to-your-image10.jpg",
    },
];

export default auctionData;
